### ISSUE TITLE
Error: Cannot read property 'map' of undefined?

### ISSUE THREAD

**Issue by gingerbeardman** [fabiospampinato/vscode-diff#1]
vscode: 1.22.1 

vcode-diff: 1.3.2

![screen shot 2018-04-07 at 10 48 48](https://user-images.githubusercontent.com/49612/38453673-4c584a46-3a51-11e8-8388-76139e7a5bc0.png)

two text files

[retroarch.cfg.txt](https://github.com/fabiospampinato/vscode-diff/files/1886242/retroarch.cfg.txt)
[retroarch.cfx.txt](https://github.com/fabiospampinato/vscode-diff/files/1886243/retroarch.cfx.txt)

**Comment by fabiospampinato** [comment]
I can reproduce this if I have no folders opened in VSC, I think this should be resolved in VSC itself: https://github.com/Microsoft/vscode/issues/47388.

**Comment by gingerbeardman** [comment]
Great, I'll watch it upstream
