### ISSUE TITLE
Improvement for the list of files (and bug?)

### ISSUE THREAD

**Issue by ppo** [fabiospampinato/vscode-diff#10]
**Currently:** The list of files to diff with contains all the files in the workspace!  
_(VS Code 1.45.1 and Diff 1.4.0)_

**Expected:** List only opened files.

**Cherry on the cake:**
- List first the file on the right, then a separator, then all the other opened files ordered as opened from left to right.
- If only 2 files opened, immediately execute the diff with the other file.
- If in split view:
  - If only 2 split views, automatically diff the files that are opened side-by-side (cf. [Atom split-diff](https://atom.io/packages/split-diff)). Maybe provide a settings option to disable this.
  - Else, list in the first part (above separator) all the current files of each view. And below the separator, separate the list of files per view.
- _(Possible?)_ Allow to select the other file by clicking on the editor tab or in the file explorer.

**Comment by fabiospampinato** [comment]
Somewhat surprisingly I don't think there's an API for retrieving a list of all opened files.

> (Possible?) Allow to select the other file by clicking on the editor tab or in the file explorer.

Single click, no, right click menu item, yes.

**Comment by ppo** [comment]
For reference, VS Code issue: [API Access to "Open Editors" #15178](https://github.com/microsoft/vscode/issues/15178) (current status: open)

**Comment by fabiospampinato** [comment]
As of v2.1 open files are listed at the top, showing other kinds of files can be disabled, and you can also enable relative paths.

> If only 2 files opened, immediately execute the diff with the other file.

This seems not worth the extra command or setting, it's just a keypress away if only a single other file is found now.

> (Possible?) Allow to select the other file by clicking on the editor tab or in the file explorer.

Let's track this in #5
