### ISSUE TITLE
does not allow selection of open buffer

### ISSUE THREAD

**Issue by enuggetry** [fabiospampinato/vscode-diff#12]
It doesn't seem to allow me to select an open buffer at all when I select the command.

**Comment by fabiospampinato** [comment]
What's an open buffer though? What is the extension doing vs what do you think it should be doing?

**Comment by enuggetry** [comment]
From the example, I believed the implication was that I can choose from the files that I have open.  Perhaps I was mistaken?

**Comment by fabiospampinato** [comment]
Ideally it should work like that, or at least currently opened files should be listed first or something, but I don't think there's any API for retrieving the list of currently open files yes.

**Comment by enuggetry** [comment]
That seems to be the problem, then.  The operation doesn't seem to match the animated demonstration you have on the main page.

**Comment by fabiospampinato** [comment]
I guess I only had those files in the workspace.

**Comment by enuggetry** [comment]
Well, if it's supposed to work with open files in the workspace, I haven't been able to get it to work.  I'm not sure how it works otherwise.  In this respect, I would say it's still an issue.
