### ISSUE TITLE
Support for vscodium additionally to visual studio code

### ISSUE THREAD

**Issue by daconstenla** [fabiospampinato/vscode-diff#13]
Hi @fabiospampinato as you might already know there is a free of telemetry copy of [visual studio code](https://github.com/microsoft/vscode) called [vscodium](https://github.com/VSCodium/vscodium) which relies on a different source for the plugins which is [open-vsx.org](https://open-vsx.org/), supporting it should be easy, according to [the documentation of their wiki](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace).

Would be lovely to have support on vscodium for your amazing extension!

**Comment by fabiospampinato** [comment]
Sorry I don't think this sort of effort is worth it on my end, feel free to redistribute my extensions yourself.
