### ISSUE TITLE
Diffing unsaved files

### ISSUE THREAD

**Issue by radiocity** [fabiospampinato/vscode-diff#14]
VSCode version: 1.52.1
Diff version: v1.4.0
OS: Windows 10 Pro 2004

Have two large sql files opened from desktop folder. No project opened. `You cannot diff an unsaved file` message popups everytime I try to diff :C

Console:
```
You cannot diff an unsaved file
onDidChangeNotification @ notificationsAlerts.ts:36
```

**Comment by fharper** [comment]
I would also love to be able to diff unsaved files.

**Comment by fabiospampinato** [comment]
That's not really possible, but the app could save a temporary file for you and diff against that. That'd be kind of a read-only thing though as editing the temporary file would be pointless.

Would you guys like to see that? 🤔

**Comment by fharper** [comment]
Yep, even if we can't modify, that would give us at least the possibility to compare them.

**Comment by tupaschoal** [comment]
I'd love seeing that too.

**Comment by Rabadash8820** [comment]
@fabiospampinato Any update on this? I too would like to be able to diff unsaved files. Tbh, I don't plan to use this extension _unless_ I'm working with unsaved files. If I had a saved file, then I would probably be working in one of my git repos and thus use `git diff` or a GUI like GitKraken for viewing diffs. The main value of an extension like this, to me, is its ability to diff adhoc text.

**Comment by fabiospampinato** [comment]
Support for diffing against untitled files is implemented in v2.
