### ISSUE TITLE
Command 'Diff: File' resulted in an error (Running the contributed command: 'diff.file' failed.)

### ISSUE THREAD

**Issue by arvinyorro** [fabiospampinato/vscode-diff#15]
My Diff extension stopped working today. Showing me this error

`Command 'Diff: File' resulted in an error (Running the contributed command: 'diff.file' failed.)`

**Comment by fabiospampinato** [comment]
@arvinyorro Can you reproduce this issue reliably?

**Comment by fabiospampinato** [comment]
Closing for lack of additional information.
