### ISSUE TITLE
Collapse blocks that have no difference

### ISSUE THREAD

**Issue by tupaschoal** [fabiospampinato/vscode-diff#16]
Have you considered collapsing the blocks of text that have no difference? For example, if you're differing two similar files with 10k lines and only line 5378 is different, it would collapse most of the lines above and below it and actually focus on the differences, which should be the purpose :D

This is very similar to what GitHub does in the PR diffs, but you can also see that in other places like diffing on vertically split files within `vi`, etc.

**Comment by fabiospampinato** [comment]
I don't think there are any APIs for this, this extension just tells vscode to open a diff editor, if it were possible there would be some settings or comments for that directly in vscode.
