### ISSUE TITLE
List only open files

### ISSUE THREAD

**Issue by PhasorLaser** [fabiospampinato/vscode-diff#18]
I would like the list to be just the "open" files meaning what I have tabs of open in the VS workspace...Otherwise the list feature is not usable, thus the point is lost

**Comment by fabiospampinato** [comment]
Last time I looked there wasn't an API for retrieving a list of open files.

**Comment by nemoDreamer** [comment]
The extension does advertise itself with:

> Diff 2 opened files with ease.

😜

--- 

If there's no API to access tabs, maybe an `exclude` setting would ease the pain of waiting for 10+ seconds for the file selector to populate, as it's retrieving everything in `.cache/jest/` and `./node-modules/.cache/` for example?

<img width="713" alt="image" src="https://github.com/fabiospampinato/vscode-diff/assets/9303/a04c3cc4-8af9-4d2a-b652-2ab662730caf">

**Comment by fabiospampinato** [comment]
Open files are now listed at the top of the list.

<img width="1002" alt="Screen Shot 2024-03-14 at 19 03 18" src="https://github.com/fabiospampinato/vscode-diff/assets/1812093/1ab875d5-4b71-4862-aa0f-714214b71e69">

If you want to remove other kinds of files you can override the `diff.include` setting, or the `diff.exclude` setting, to make sure nothing passes those filters.

Potentially a dedicate command that only lists open files can be added, but it seems a bit superflous?

**Comment by fabiospampinato** [comment]
This is customizable in v2.1, if you only want to see open files use these settings:

```
  "diff.showUntitledFiles": true,
  "diff.showOpenFiles": true,
  "diff.showFoundFiles": false,
  "diff.showFoundRelativeFiles": false
```
