### ISSUE TITLE
Open target file with relative file path from source file

### ISSUE THREAD

**Issue by xxrlzzz** [fabiospampinato/vscode-diff#19]
As `diff` always from current file  and some other file, is will be very useful if I can to locate file from a relative path.

**Comment by fabiospampinato** [comment]
There's a setting for this in v2.1, if you set `diff.showFoundRelativeFiles` then relative versions of paths, that start with either `./` or `../`, will be visible in the selector. The other paths can be disabled with a setting `"diff.showFoundFiles": false`
