### ISSUE TITLE
Ability to edit both editors

### ISSUE THREAD

**Issue by dandv** [fabiospampinato/vscode-diff#2]
See https://github.com/ryu1kn/vscode-partial-diff/issues/30

**Comment by fabiospampinato** [comment]
So what you want is to have both panels editable, right?

I'm afraid there's no API for doing this at the moment, currently only the rightmost editor is actually editable I think.

**Comment by dandv** [comment]
Rightmost editable would be much better than none editable :)

**Comment by fabiospampinato** [comment]
Isn't it editable already though?

**Comment by kafran** [comment]
The rightmost editor is editable already.

**Comment by ppo** [comment]
Both are editable… at least in VS Code 1.45.1.

**Comment by fabiospampinato** [comment]
> Both are editable… at least in VS Code 1.45.1.

Closing this then, I think they might have enabled this in the latest minor release.
