### ISSUE TITLE
CSV files are not detected

### ISSUE THREAD

**Issue by yisen-cai** [fabiospampinato/vscode-diff#21]
I'm using Diff to check many kinds type file, but only csv file can't show diff file option list, the file is real exists, change it's type is ok, it only shows without csv type.

**Comment by mtazzari** [comment]
The tool is great, but I also find that it doesn't work with `.csv` files.
Is it possible to have a quick fix for that? It'd be super helpful.
Many thanks!

**Comment by fabiospampinato** [comment]
That's strange, maybe .csv files are detect as binary files internally by mistake. I'll look into that.

**Comment by 06000208** [comment]
can confirm this is the case, csv files aren't showing up in the list, but you can rename them to txt and it'll work

**Comment by fabiospampinato** [comment]
I've rewritten the extension, this is fixed in v2. "csv" files were considered to be binary in the dependency the extension uses to detect binary files.
