### ISSUE TITLE
Donation popup

### ISSUE THREAD

**Issue by ricardobeat** [fabiospampinato/vscode-diff#22]
Just got a popup requesting money inside VSCode, from this extension. Uninstalled immediately.

The extension hasn't had an update in 1.5 years, why does it even need funding?

**Comment by fabiospampinato** [comment]
It doesn't _need_ it, but you know there are some open issues, the extension seems to be used by many people, I'm currently working on a startup and not really have any sustainable level of income, I thought it might have been a win-win kind of situation. It didn't work out particularly well at all, so I'll probably just remove the popup eventually.
