### ISSUE TITLE
Showing recently opened files first

### ISSUE THREAD

**Issue by maximilianmordig** [fabiospampinato/vscode-diff#23]
Typing the paths in the diff dialog is not very handy. It would be good if there is an option to sort by most recently opened (similar to Cmd+Shift+P to open a file).

The diff option should also be available when rightclicking on a file in the vscode file viewer.

**Comment by fabiospampinato** [comment]
Let's track the context menu suggestion here https://github.com/fabiospampinato/vscode-diff/issues/5

**Comment by fabiospampinato** [comment]
Implemented in v2, for _currently open_ files. As far as I know there is no API for _recently open_ files.

<img width="1002" alt="Screen Shot 2024-03-14 at 19 03 18" src="https://github.com/fabiospampinato/vscode-diff/assets/1812093/945a0d8e-a30e-4325-baf1-5deb23bacd9d">
