### ISSUE TITLE
Smarter Diff for JSON files

### ISSUE THREAD

**Issue by sp71** [fabiospampinato/vscode-diff#24]
Comparing two JSON files would be great where it detects if the same key and value match regardless of the order

**a.json**

```
{
  "foo": 1,
  "bar": 2
}
```

**b.json**
```
{
  "bar": 2,
  "foo": 1
}
```

**Comment by fabiospampinato** [comment]
That'd be kinda cool, but that's another kind of diffing, it'd probably be better to have a dedicated extension for that.
