### ISSUE TITLE
Support `.gitignore`

### ISSUE THREAD

**Issue by muuvmuuv** [fabiospampinato/vscode-diff#4]
I have noticed that it also shows .git files etc. Would be great if I could turn an option on to tell diff that it should ignore certain files or by file.

**Comment by fabiospampinato** [comment]
Files from `./.git` shouldn't be displayed 🤔 If that's the case I'd consider this a bug.

Supporting `.gitignore` sounds like a good addition, PRs welcome 👍

**Comment by okwme** [comment]
for me it's also running a search on all files inside of node_modules, this is taking a really long time and actually breaking

**Comment by stefano-b** [comment]
I also think that ignoring the content of node_modules by default (or at least letting the user chose to do so with an option, maybe?) would be a nice addition and would speed up its use.

**Comment by muuvmuuv** [comment]
`.git`-files are not longer in the tree but I agree with @stefano-b that node_modules shouldn't be in the list as well. Plus I would ignore common directories like:

- tmp
- .tmp
- cache
- .cache

**Comment by muuvmuuv** [comment]
I think showing opened files in the tree first would be a nice enhancement as well

**Comment by fabiospampinato** [comment]
This extension should respect the "files.exclude" setting, you should put stuff to exclude there.

**Comment by fabiospampinato** [comment]
This is supported in v2, there's a new setting, `diff.ignore`, to set the files to consider as gitignore files.
