### ISSUE TITLE
Distinguish files by path when filename is identical

### ISSUE THREAD

**Issue by ChildishGiant** [fabiospampinato/vscode-diff#7]
When multiple files with the same name are open vscode shows the path so you know which is which. Could we have some clarification which file is which when diffing two identically named files?

![image](https://user-images.githubusercontent.com/13716824/73496828-55719180-43b1-11ea-8c39-c3fedfd5f788.png)

**Comment by BananaAcid** [comment]
Messing it up all the time. This is quite some problem.

**Comment by fabiospampinato** [comment]
Fixed in v1.4.1, a bit verbosely, but it will do it for now.
